"""Domain contracts shared by API, agents, tools, and evaluation."""

from crossborder_domain.agents import (
    AgentName,
    AgentRequest,
    AgentResult,
    AgentResultStatus,
    EvidenceReference,
    RecommendedAction,
    RiskFinding,
    RiskSeverity,
    WorkflowStatus,
)
from crossborder_domain.common import Money, TimeRange
from crossborder_domain.data import (
    AdvertisingIngestionPreview,
    AdvertisingRecord,
    ColumnMapping,
    CostRecord,
    CreativeRecord,
    CurrencyRateRecord,
    DataDomain,
    DataQualityIssue,
    DatasetIngestionPreview,
    ImportStatus,
    IngestionImportResult,
    IngestionLineage,
    InventoryRecord,
    MappingStatus,
    OrderRecord,
    ProductRecord,
    QualitySeverity,
    RefundRecord,
    ReviewRecord,
    StandardRecord,
)

__all__ = [
    "AdvertisingIngestionPreview",
    "AdvertisingRecord",
    "AgentName",
    "AgentRequest",
    "AgentResult",
    "AgentResultStatus",
    "ColumnMapping",
    "CostRecord",
    "CreativeRecord",
    "CurrencyRateRecord",
    "DataDomain",
    "DataQualityIssue",
    "DatasetIngestionPreview",
    "EvidenceReference",
    "ImportStatus",
    "IngestionImportResult",
    "IngestionLineage",
    "InventoryRecord",
    "MappingStatus",
    "Money",
    "OrderRecord",
    "ProductRecord",
    "QualitySeverity",
    "RecommendedAction",
    "RefundRecord",
    "ReviewRecord",
    "RiskFinding",
    "RiskSeverity",
    "StandardRecord",
    "TimeRange",
    "WorkflowStatus",
]
